"""Report generators for ACRF assessment results."""

from __future__ import annotations

import json
from typing import Literal

from acrf.core.models import AssessmentResult


def to_markdown(result: AssessmentResult) -> str:
    lines: list[str] = []
    lines.append(f"# ACRF Assessment  - {result.system_name}")
    lines.append("")
    lines.append(f"- **Methodology version:** {result.acrf_version}")
    if result.assessment_date:
        lines.append(f"- **Assessment date:** {result.assessment_date}")
    lines.append(f"- **Overall mean level:** {result.overall_score():.2f}")
    lines.append("")

    lines.append("## Risk dimension scores")
    lines.append("")
    lines.append("| # | Risk Dimension | AIVSS | Claimed | Awarded |")
    lines.append("|---|----------------|-------|---------|---------|")
    for r in result.dimension_results:
        lines.append(
            f"| {r.dimension.acrf_id} | {r.dimension.display_name} | "
            f"{r.dimension.aivss_score} ({r.dimension.aivss_severity}) | "
            f"{r.claimed_level.value} | {r.awarded_level.value} |"
        )
    lines.append("")

    lines.append("## Per-dimension findings")
    lines.append("")
    for r in result.dimension_results:
        lines.append(f"### {r.dimension.acrf_id}  - {r.dimension.display_name}")
        lines.append("")
        lines.append(f"- **OWASP Agentic:** {r.dimension.owasp_agentic}")
        lines.append(f"- **OWASP MCP:** {r.dimension.owasp_mcp}")
        lines.append(f"- **AIVSS:** {r.dimension.aivss_score} ({r.dimension.aivss_severity})")
        lines.append(f"- **Defense pattern:** {r.dimension.defense_pattern}")
        lines.append(f"- Claimed level: **{r.claimed_level.value}**")
        lines.append(f"- Awarded level: **{r.awarded_level.value}**")
        if r.notes:
            lines.append("")
            lines.append("**Notes:**")
            for n in r.notes:
                lines.append(f"- {n}")
        if r.gaps:
            lines.append("")
            lines.append("**Evidence gaps:**")
            for g in r.gaps:
                lines.append(f"- {g}")
        lines.append("")

    lines.append("## Remediation backlog")
    lines.append("")
    if not result.remediation_backlog:
        lines.append("_No outstanding items; all dimensions at level 4._")
    else:
        for i, item in enumerate(result.remediation_backlog, 1):
            lines.append(f"{i}. {item}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by the ACRF reference tool. The methodology is described "
        "at [https://github.com/kannasekar-alt/acrf](https://github.com/kannasekar-alt/acrf)._"
    )

    return "\n".join(lines)


def to_json(result: AssessmentResult) -> str:
    def default(o):
        # Handle enums that aren't natively JSON-serializable via asdict.
        if hasattr(o, "value"):
            return o.value
        raise TypeError(f"Cannot serialize {type(o).__name__}")

    payload = {
        "system_name": result.system_name,
        "acrf_version": result.acrf_version,
        "assessment_date": result.assessment_date,
        "overall_score": result.overall_score(),
        "dimension_results": [
            {
                "acrf_id": r.dimension.acrf_id,
                "dimension": r.dimension.value,
                "dimension_display_name": r.dimension.display_name,
                "owasp_agentic": r.dimension.owasp_agentic,
                "owasp_mcp": r.dimension.owasp_mcp,
                "aivss_score": r.dimension.aivss_score,
                "aivss_severity": r.dimension.aivss_severity,
                "defense_pattern": r.dimension.defense_pattern,
                "claimed_level": r.claimed_level.value,
                "awarded_level": r.awarded_level.value,
                "gaps": r.gaps,
                "notes": r.notes,
            }
            for r in result.dimension_results
        ],
        "remediation_backlog": result.remediation_backlog,
    }
    return json.dumps(payload, indent=2)


def render(result: AssessmentResult, format: Literal["markdown", "json"] = "markdown") -> str:
    if format == "markdown":
        return to_markdown(result)
    if format == "json":
        return to_json(result)
    raise ValueError(f"Unknown format: {format}")
